//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficSignalLight
{
    using System;
    using System.Collections.Generic;
    
    public partial class LightPattern
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LightPattern()
        {
            this.SignTemplates = new HashSet<SignTemplate>();
            this.TemplatePatterns = new HashSet<TemplatePattern>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int Red { get; set; }
        public int Green { get; set; }
        public int Amber { get; set; }
        public bool GreenAmberOverlab { get; set; }
        public int Pedstrain { get; set; }
        public bool ShowSigneCounter { get; set; }
        public bool ShowPedstrainCounter { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SignTemplate> SignTemplates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TemplatePattern> TemplatePatterns { get; set; }
    }
}
