//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficSignalLight
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TraficLightSignesEntities2 : DbContext
    {
        public TraficLightSignesEntities2()
            : base("name=TraficLightSignesEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<Governerate> Governerates { get; set; }
        public virtual DbSet<LightPattern> LightPatterns { get; set; }
        public virtual DbSet<SigneControlBox> SigneControlBoxes { get; set; }
        public virtual DbSet<SignTemplate> SignTemplates { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Template> Templates { get; set; }
        public virtual DbSet<TemplatePattern> TemplatePatterns { get; set; }
    }
}
