//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficSignalLight
{
    using System;
    using System.Collections.Generic;
    
    public partial class SigneControlBox
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SigneControlBox()
        {
            this.SignTemplates = new HashSet<SignTemplate>();
        }
    
        public int ID { get; set; }
        public int AreaID { get; set; }
        public int LightPatternID { get; set; }
        public string IPAddress { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public string DirectionOne { get; set; }
        public string DirectionTwo { get; set; }
    
        public virtual Area Area { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SignTemplate> SignTemplates { get; set; }
    }
}
