//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficSignalLight
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplatePattern
    {
        public int ID { get; set; }
        public int TemplateID { get; set; }
        public int PetternID { get; set; }
        public System.TimeSpan StartFrom { get; set; }
        public System.TimeSpan FinishBy { get; set; }
    
        public virtual LightPattern LightPattern { get; set; }
        public virtual Template Template { get; set; }
    }
}
